/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ControlCenter.java
 *
 * Created on May 3, 2009, 12:01:20 PM
 */
package ccfdgui;

import baumwelch.Detector;
import baumwelch.HMM;
import javax.swing.JLabel;
import javax.swing.JTextField;
import kmeans.kMeans;

/**
 *
 * @author sudeep
 */
public class ControlCenter extends javax.swing.JFrame {

    /** Creates new form ControlCenter */
    public ControlCenter() {
        initComponents();
        piLabel=new JLabel[10];
        piTextField=new JTextField[10];
        piLabel[0] = pi0Label;
        piLabel[1] = pi1Label;
        piLabel[2] = pi2Label;
        piLabel[3] = pi3Label;
        piLabel[4] = pi4Label;
        piLabel[5] = pi5Label;
        piLabel[6] = pi6Label;
        piLabel[7] = pi7Label;
        piLabel[8] = pi8Label;
        piLabel[9] = pi9Label;

        piTextField[0] = pi0TextField;
        piTextField[1] = pi1TextField;
        piTextField[2] = pi2TextField;
        piTextField[3] = pi3TextField;
        piTextField[4] = pi4TextField;
        piTextField[5] = pi5TextField;
        piTextField[6] = pi6TextField;
        piTextField[7] = pi7TextField;
        piTextField[8] = pi8TextField;
        piTextField[9] = pi9TextField;
        

        pi3Label.setVisible(false);
        pi4Label.setVisible(false);
        pi5Label.setVisible(false);
        pi6Label.setVisible(false);
        pi7Label.setVisible(false);
        pi8Label.setVisible(false);
        pi9Label.setVisible(false);

        pi3TextField.setVisible(false);
        pi4TextField.setVisible(false);
        pi5TextField.setVisible(false);
        pi6TextField.setVisible(false);
        pi7TextField.setVisible(false);
        pi8TextField.setVisible(false);
        pi9TextField.setVisible(false);

        

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hmmStatesLabel = new javax.swing.JLabel();
        numClusterLabel = new javax.swing.JLabel();
        controlCenterSubmit = new javax.swing.JButton();
        controlCenterReset = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        numStatesComboBox = new javax.swing.JComboBox();
        numClusterComboBox = new javax.swing.JComboBox();
        pi2Label = new javax.swing.JLabel();
        pi3Label = new javax.swing.JLabel();
        pi0Label = new javax.swing.JLabel();
        pi4Label = new javax.swing.JLabel();
        pi5Label = new javax.swing.JLabel();
        pi6Label = new javax.swing.JLabel();
        pi1Label = new javax.swing.JLabel();
        pi7Label = new javax.swing.JLabel();
        pi9Label = new javax.swing.JLabel();
        pi8Label = new javax.swing.JLabel();
        pi0TextField = new javax.swing.JTextField();
        pi1TextField = new javax.swing.JTextField();
        pi3TextField = new javax.swing.JTextField();
        pi5TextField = new javax.swing.JTextField();
        pi4TextField = new javax.swing.JTextField();
        pi2TextField = new javax.swing.JTextField();
        pi6TextField = new javax.swing.JTextField();
        pi7TextField = new javax.swing.JTextField();
        pi8TextField = new javax.swing.JTextField();
        pi9TextField = new javax.swing.JTextField();
        piCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        thresholdValueLabel = new javax.swing.JLabel();
        mobilenoCustomer = new javax.swing.JLabel();
        thresholdValueTextField = new javax.swing.JTextField();
        mobileNoTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HMM Control Center");
        setMinimumSize(new java.awt.Dimension(10, 10));
        setResizable(false);

        hmmStatesLabel.setText("Number of HMM States");

        numClusterLabel.setText("Number of Clusters");

        controlCenterSubmit.setText("Submit");
        controlCenterSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlCenterSubmitActionPerformed(evt);
            }
        });

        controlCenterReset.setText("Reset");
        controlCenterReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlCenterResetActionPerformed(evt);
            }
        });

        numStatesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "4", "5", "6", "7", "8", "9", "10" }));
        numStatesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numStatesComboBoxActionPerformed(evt);
            }
        });

        numClusterComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "4", "5", "6", "7", "8", "9", "10" }));
        numClusterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numClusterComboBoxActionPerformed(evt);
            }
        });

        pi2Label.setText("pi[2]");

        pi3Label.setText("pi[3]");

        pi0Label.setText("pi[0]");

        pi4Label.setText("pi[4]");

        pi5Label.setText("pi[5]");

        pi6Label.setText("pi[6]");

        pi1Label.setText("pi[1]");

        pi7Label.setText("pi[7]");

        pi9Label.setText("pi[9]");

        pi8Label.setText("pi[8]");

        pi8TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pi8TextFieldActionPerformed(evt);
            }
        });

        piCheckBox.setText("Use same value of Pi for all the states");
        piCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piCheckBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Initial State Probability Values");

        jLabel2.setText("HMM Initial Parameters");

        thresholdValueLabel.setText("Set the Threshold Value");

        mobilenoCustomer.setText("Enter the mobile no of customer");

        thresholdValueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thresholdValueTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Detection Phase Parameters");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pi0Label)
                                    .addComponent(pi4Label)
                                    .addComponent(pi3Label)
                                    .addComponent(pi2Label)
                                    .addComponent(pi1Label))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pi4TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(pi2TextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(pi3TextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(pi0TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(pi1TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                                .addGap(176, 176, 176)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pi5Label)
                                    .addComponent(pi7Label)
                                    .addComponent(pi6Label)
                                    .addComponent(pi8Label)
                                    .addComponent(pi9Label))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pi9TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(pi8TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(pi7TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(pi6TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(pi5TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hmmStatesLabel)
                            .addComponent(numClusterLabel))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(numStatesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numClusterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thresholdValueLabel)
                            .addComponent(mobilenoCustomer))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mobileNoTextField)
                            .addComponent(thresholdValueTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(controlCenterSubmit)
                        .addGap(78, 78, 78)
                        .addComponent(controlCenterReset))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(piCheckBox)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hmmStatesLabel)
                    .addComponent(numStatesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numClusterLabel)
                    .addComponent(numClusterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thresholdValueLabel)
                    .addComponent(thresholdValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobilenoCustomer)
                    .addComponent(mobileNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pi0Label)
                    .addComponent(pi5TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pi5Label, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(pi0TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pi1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pi1Label))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pi2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pi2Label))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pi3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pi3Label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pi4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pi4Label)
                            .addComponent(pi9TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pi9Label)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pi6TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pi6Label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pi7TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pi7Label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pi8TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pi8Label))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(piCheckBox)
                .addGap(7, 7, 7)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(controlCenterReset)
                    .addComponent(controlCenterSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void controlCenterSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlCenterSubmitActionPerformed
        int noOfStates, noOfClusters;

       
        noOfStates = Integer.parseInt((String) numStatesComboBox.getSelectedItem());
        noOfClusters = Integer.parseInt((String) numClusterComboBox.getSelectedItem());
        HMM hmm = new HMM(noOfStates, noOfClusters);
        hmm.setPhoneNo(mobileNoTextField.getText());
        Detector detector =new Detector(hmm);
        detector.setThreshold(Double.parseDouble(thresholdValueTextField.getText()));
        detector.setMobileNo(mobileNoTextField.getText());

        kMeans km = new kMeans(noOfClusters);
        double piValue[]=new double[10];
        for(int i=0;i<noOfStates;i++)
        {
            if(piCheckBox.isSelected())
            {
                piValue[i]=Double.parseDouble(piTextField[0].getText());
            }
            else piValue[i]=Double.parseDouble(piTextField[i].getText());
        }
        hmm.initializeHMM(piValue);

        this.setVisible(false);

        HmmTraining hmmTrainingFrame=new HmmTraining(hmm,km,detector);
        hmmTrainingFrame.setVisible(true);



    }//GEN-LAST:event_controlCenterSubmitActionPerformed

    private void controlCenterResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlCenterResetActionPerformed
        numStatesComboBox.setSelectedIndex(0);
        numClusterComboBox.setSelectedIndex(0);
        thresholdValueTextField.setText("");
        mobileNoTextField.setText("");
        
    }//GEN-LAST:event_controlCenterResetActionPerformed

    private void numClusterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numClusterComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numClusterComboBoxActionPerformed

    private void piCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piCheckBoxActionPerformed
        if(piCheckBox.isSelected())
        {
            for(int i=1;i<10;i++)
            {
                piTextField[i].setEnabled(false);
            }

        }
        else{
            for(int i=1;i<10;i++)
            {
                piTextField[i].setEnabled(true);
            }
        }
        //System.out.println("action ");
}//GEN-LAST:event_piCheckBoxActionPerformed

    private void pi8TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pi8TextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_pi8TextFieldActionPerformed

    private void numStatesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numStatesComboBoxActionPerformed

        int noOfStates=Integer.parseInt((String) numStatesComboBox.getSelectedItem());
        for(int i=0; i<noOfStates; i++)
        {
            piLabel[i].setVisible(true);
            piTextField[i].setVisible(true);
        }
        piCheckBox.setVisible(true);
        for(int i=noOfStates; i<10; i++)
        {
            piLabel[i].setVisible(false);
            piTextField[i].setVisible(false);
        }

    }//GEN-LAST:event_numStatesComboBoxActionPerformed

    private void thresholdValueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thresholdValueTextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_thresholdValueTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ControlCenter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton controlCenterReset;
    private javax.swing.JButton controlCenterSubmit;
    private javax.swing.JLabel hmmStatesLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField mobileNoTextField;
    private javax.swing.JLabel mobilenoCustomer;
    private javax.swing.JComboBox numClusterComboBox;
    private javax.swing.JLabel numClusterLabel;
    private javax.swing.JComboBox numStatesComboBox;
    private javax.swing.JLabel pi0Label;
    private javax.swing.JTextField pi0TextField;
    private javax.swing.JLabel pi1Label;
    private javax.swing.JTextField pi1TextField;
    private javax.swing.JLabel pi2Label;
    private javax.swing.JTextField pi2TextField;
    private javax.swing.JLabel pi3Label;
    private javax.swing.JTextField pi3TextField;
    private javax.swing.JLabel pi4Label;
    private javax.swing.JTextField pi4TextField;
    private javax.swing.JLabel pi5Label;
    private javax.swing.JTextField pi5TextField;
    private javax.swing.JLabel pi6Label;
    private javax.swing.JTextField pi6TextField;
    private javax.swing.JLabel pi7Label;
    private javax.swing.JTextField pi7TextField;
    private javax.swing.JLabel pi8Label;
    private javax.swing.JTextField pi8TextField;
    private javax.swing.JLabel pi9Label;
    private javax.swing.JTextField pi9TextField;
    private javax.swing.JCheckBox piCheckBox;
    private javax.swing.JLabel thresholdValueLabel;
    private javax.swing.JTextField thresholdValueTextField;
    // End of variables declaration//GEN-END:variables
    
    private javax.swing.JLabel piLabel[];
    private javax.swing.JTextField piTextField[];
}
