/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Detection.java
 *
 * Created on May 5, 2009, 10:58:44 AM
 */
package ccfdgui;

import baumwelch.Detector;
import baumwelch.HMM;
import client.SendSms;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import kmeans.kMeans;

/**
 *
 * @author sudeep
 */
public class Detection extends javax.swing.JFrame {

    private HMM hmm;
    private kMeans km;
    private Detector detector;
    double alpha = 0;
    private HmmTraining hmmTBack;

    /** Creates new form Detection */
    public Detection() {
        initComponents();
    }

    public Detection(HMM hmm, kMeans km, Detector detector) {
        initComponents();
        this.hmm = hmm;
        this.km = km;
        this.detector = detector;
    }

    public Detection(HMM hmm, kMeans km, Detector detector, HmmTraining hmmT) {
        initComponents();
        this.hmm = hmm;
        this.km = km;
        this.detector = detector;
        this.hmmTBack = hmmT;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newTransactionLabel = new javax.swing.JLabel();
        newTransactionTextField = new javax.swing.JTextField();
        newTransactionSubmitButton = new javax.swing.JButton();
        newTransactionResetButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        evaluationResultPanel = new javax.swing.JPanel();
        evaluationResultLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        oldCustomerProfileLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        newCustomerProfileLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fraud Detection");

        newTransactionLabel.setText("Enter new transaction");

        newTransactionSubmitButton.setText("Submit ");
        newTransactionSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTransactionSubmitButtonActionPerformed(evt);
            }
        });

        newTransactionResetButton.setText("Reset");

        evaluationResultLabel.setText("Fraud Evaluation Result will be displayed here");

        jLabel1.setText("FRAUD EVALUATION RESULT");

        jLabel2.setText("Old Customer Profile");

        oldCustomerProfileLabel.setText("profile wil b displayed here");

        jLabel3.setText("New Customer Profile");

        newCustomerProfileLabel.setText("profile wi b displayed here");

        backButton.setText("back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout evaluationResultPanelLayout = new javax.swing.GroupLayout(evaluationResultPanel);
        evaluationResultPanel.setLayout(evaluationResultPanelLayout);
        evaluationResultPanelLayout.setHorizontalGroup(
            evaluationResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(evaluationResultPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(evaluationResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(evaluationResultPanelLayout.createSequentialGroup()
                        .addComponent(evaluationResultLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(backButton))
                    .addGroup(evaluationResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(oldCustomerProfileLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(evaluationResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newCustomerProfileLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        evaluationResultPanelLayout.setVerticalGroup(
            evaluationResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(evaluationResultPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oldCustomerProfileLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newCustomerProfileLabel)
                .addGap(18, 18, 18)
                .addGroup(evaluationResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(evaluationResultLabel)
                    .addComponent(backButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(newTransactionLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(newTransactionSubmitButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newTransactionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newTransactionResetButton))
                .addContainerGap(199, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(evaluationResultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newTransactionLabel)
                    .addComponent(newTransactionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newTransactionSubmitButton)
                    .addComponent(newTransactionResetButton))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(evaluationResultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newTransactionSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTransactionSubmitButtonActionPerformed

        double oldCustomerProfile[] = km.customerProfile(hmm);
        StringBuffer oldCustomerProfileStringBuffer = new StringBuffer();
        StringBuffer newCustomerProfileStringBuffer = new StringBuffer();
        boolean isFraud = false;

        try {
            alpha = detector.calculateAlpha(Integer.parseInt(newTransactionTextField.getText()), km);
        } catch (IOException ex) {
            Logger.getLogger(Detection.class.getName()).log(Level.SEVERE, null, ex);
        }

        isFraud = detector.fraudEvaluation(alpha, oldCustomerProfile,Integer.parseInt(newTransactionTextField.getText()));
        km.commit(isFraud);

        double newCustomerProfile[] = km.customerProfile(hmm);
        oldCustomerProfileStringBuffer.append("<");
        for (int i = 0; i < oldCustomerProfile.length; i++) {
            oldCustomerProfileStringBuffer.append(oldCustomerProfile[i] + ",");
        }
        oldCustomerProfileStringBuffer.append(">");

        newCustomerProfileStringBuffer.append("<");
        for (int i = 0; i < oldCustomerProfile.length; i++) {
            newCustomerProfileStringBuffer.append(oldCustomerProfile[i] + ",");
        }
        newCustomerProfileStringBuffer.append(">");

        oldCustomerProfileLabel.setText(oldCustomerProfileStringBuffer.toString());
        newCustomerProfileLabel.setText(newCustomerProfileStringBuffer.toString());
        if (isFraud) {

            evaluationResultLabel.setText("Fraud has been detected");
            SendSms.sendAlertSms(hmm.getPhoneNo(), "Transaction carried by you looks suspicious. " +
                    "It has been labeled as FRAUD by FDS. " +
                    "Please confirm your transaction");




            try {
                //System.out.println("before read data");
                km.readData();
            } catch (Exception e) {
                System.err.println(e);
                System.exit(-1);
            }

            km.runKMeans();
            km.outputProcessor();

            hmm.initializeHMM();

            try {
                hmm.train(hmm.readFile(), 100);
                hmm.print();
            } catch (IOException ex) {
            }



        } else {



            try {
                //System.out.println("before read data");
                km.readData();
            } catch (Exception e) {
                System.err.println(e);
                System.exit(-1);
            }

            km.runKMeans();
            km.outputProcessor();


            hmm.initializeHMM();

            try {
                hmm.train(hmm.readFile(), 100);
                hmm.print();
            } catch (IOException ex) {
            }




            evaluationResultLabel.setText("No Fraud. Genuine Transaction");
        }
}//GEN-LAST:event_newTransactionSubmitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        hmmTBack.setVisible(true);


    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Detection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel evaluationResultLabel;
    private javax.swing.JPanel evaluationResultPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel newCustomerProfileLabel;
    private javax.swing.JLabel newTransactionLabel;
    private javax.swing.JButton newTransactionResetButton;
    private javax.swing.JButton newTransactionSubmitButton;
    private javax.swing.JTextField newTransactionTextField;
    private javax.swing.JLabel oldCustomerProfileLabel;
    // End of variables declaration//GEN-END:variables
}
