/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HmmTraining.java
 *
 * Created on May 3, 2009, 4:43:16 PM
 */
package ccfdgui;

import baumwelch.Detector;
import baumwelch.HMM;
import java.io.IOException;
import javax.swing.JOptionPane;
import kmeans.kMeans;

/**
 *
 * @author sudeep
 */
public class HmmTraining extends javax.swing.JFrame {

    private HMM hmm;
    private kMeans km;
    private Detector detector;

    /** Creates new form HmmTraining */
    public HmmTraining() {
        initComponents();
        hmmTrainPanel.setVisible(false);
        proceedPanel.setVisible(false);
    }

    public HmmTraining(HMM hmm, kMeans km, Detector detector) {
        initComponents();
        this.hmm = hmm;
        this.km = km;
        this.detector = detector;
        hmmTrainPanel.setVisible(false);
        proceedPanel.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trainHmmMessageBox = new javax.swing.JOptionPane();
        clusterInputFile = new javax.swing.JFileChooser();
        selectInputButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        selectedFilePath = new javax.swing.JLabel();
        clusterButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        hmmTrainPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        trainHmmButton = new javax.swing.JButton();
        proceedPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        proceedButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HMM Training");

        selectInputButton.setText("Select");
        selectInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectInputButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Clustering");

        jLabel2.setText("Select Input File for Clustering");

        selectedFilePath.setText("remove text later         ");

        clusterButton.setText("Perform Clustering");
        clusterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clusterButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("HMM Training");

        trainHmmButton.setText("Train HMM");
        trainHmmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainHmmButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hmmTrainPanelLayout = new javax.swing.GroupLayout(hmmTrainPanel);
        hmmTrainPanel.setLayout(hmmTrainPanelLayout);
        hmmTrainPanelLayout.setHorizontalGroup(
            hmmTrainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hmmTrainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hmmTrainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(trainHmmButton))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        hmmTrainPanelLayout.setVerticalGroup(
            hmmTrainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hmmTrainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(trainHmmButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("HMM Training Completed.  Now you can proceeed to Detection Phase");

        proceedButton.setText("Proceed");
        proceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout proceedPanelLayout = new javax.swing.GroupLayout(proceedPanel);
        proceedPanel.setLayout(proceedPanelLayout);
        proceedPanelLayout.setHorizontalGroup(
            proceedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proceedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(proceedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(proceedButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        proceedPanelLayout.setVerticalGroup(
            proceedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proceedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proceedButton)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clusterButton)
                            .addComponent(selectedFilePath)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(selectInputButton)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(proceedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hmmTrainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(selectInputButton)
                .addGap(18, 18, 18)
                .addComponent(selectedFilePath)
                .addGap(18, 18, 18)
                .addComponent(clusterButton)
                .addGap(54, 54, 54)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hmmTrainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(proceedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectInputButtonActionPerformed
        clusterInputFile.showOpenDialog(selectInputButton);
        //System.out.println(clusterInputFile.getSelectedFile());
        this.km.setInputFileName(clusterInputFile.getSelectedFile().getAbsolutePath());
        selectedFilePath.setText("File selected is: " + clusterInputFile.getSelectedFile().getAbsolutePath());
}//GEN-LAST:event_selectInputButtonActionPerformed

    private void clusterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clusterButtonActionPerformed

        try {
            //System.out.println("before read data");
            km.readData();
        } catch (Exception e) {
            System.err.println(e);
            System.exit(-1);
        }

        km.runKMeans();
        km.outputProcessor();
        JOptionPane.showMessageDialog(this, "clustering done");
        hmmTrainPanel.setVisible(true);
    }//GEN-LAST:event_clusterButtonActionPerformed

    @SuppressWarnings("static-access")
    private void trainHmmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainHmmButtonActionPerformed
        try {
            hmm.readFile();
        } catch (IOException ex) {
        }

        try {
            hmm.train(hmm.readFile(), 500);
            hmm.print();
        } catch (IOException ex) {
        }
        trainHmmMessageBox.showMessageDialog(this, "HMM Training Completed");

        proceedPanel.setVisible(true);

    }//GEN-LAST:event_trainHmmButtonActionPerformed

    private void proceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedButtonActionPerformed
        
        this.setVisible(false);
        
        Detection detectionFrame = new Detection(hmm, km, detector,this);
        detectionFrame.setVisible(true);


    }//GEN-LAST:event_proceedButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new HmmTraining().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clusterButton;
    private javax.swing.JFileChooser clusterInputFile;
    private javax.swing.JPanel hmmTrainPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton proceedButton;
    private javax.swing.JPanel proceedPanel;
    private javax.swing.JButton selectInputButton;
    private javax.swing.JLabel selectedFilePath;
    private javax.swing.JButton trainHmmButton;
    private javax.swing.JOptionPane trainHmmMessageBox;
    // End of variables declaration//GEN-END:variables
}
